# ================================
# Server Configuration
# ================================
server:
  port: 9999
  servlet:
    context-path: /api/v1

# ================================
# DB
# ================================
spring:
  datasource:
    url: jdbc:mysql://34.121.176.144:3306/elite_brain_db
    username: elitebrain
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  # ================================
  # Mail
  # ================================

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentuanthanhbg123@gmail.com
    password: mvzzgldriigpmrcy
  #    properties:
  #        mail:
  #          smtp:
  #            auth: true
  #            starttls:
  #              enable: true
# ================================
# JPA
# ================================
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
# ================================
# JWT
# ================================
security:
  jwt:
    secret-key: 34743777217A25432A462D4C614E645267556B586E3272357538782F413F4428
    expiration: 86400000
    refresh-token:
      expiration: 604800000
# ================================
# Swagger
# ================================
springdoc:
  swagger-ui:
    path: /swagger-ui.html